#ifndef PYOS_KERNEL_H
#define PYOS_KERNEL_H

#include "types.h"

/* Filled by generated glue from Python */
typedef struct {
    u32 stack_top;
    u32 heap_start;
    u32 heap_size;
    pyos_bool enable_interrupts;
    pyos_bool has_keypress_handler;
} KernelConfig;

extern KernelConfig g_kernel_config;

/* Generated by Python bridge */
void pyos_user_boot(void);
void pyos_user_keypress(char ch, u8 scancode);

void kmain(void);

#endif
