"""
pyOS Code Generator — Python boot ops -> C glue calling the C runtime
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Dict, List, Tuple

from ..drivers.screen import Screen
from ..drivers.keyboard import Keyboard
from ..memory.manager import Memory
from ..interrupts.handler import Interrupts
from ..syscalls.handler import SysCall

if TYPE_CHECKING:
    from ..kernel import Kernel


class CodeGenerator:
    """
    Runs boot functions at build time, records Screen/Memory ops,
    and emits a small C glue file that calls the freestanding runtime.
    """

    def __init__(self, kernel: "Kernel"):
        self.kernel = kernel
        self.arch = kernel.config.arch.value
        self._strings: List[Tuple[str, str]] = []
        self._func_ops: Dict[str, list] = {}
        self._string_counter = 0
        self._has_keypress = bool(kernel._keypress_handlers)
        self._symbol_map: List[Dict[str, str]] = []

    def generate(self) -> str:
        """Generate C glue source (not Assembly)."""
        if self.arch != "x86":
            raise ValueError(
                "Only arch='x86' is supported right now.\n"
                "  Why: the freestanding C runtime and bootloader are 32-bit.\n"
                "  Hint: use Kernel(arch='x86')"
            )

        self._strings = []
        self._func_ops = {}
        self._string_counter = 0
        self._symbol_map = []

        sorted_funcs = sorted(self.kernel._boot_functions, key=lambda x: x.priority)
        for boot_func in sorted_funcs:
            Screen._reset()
            Keyboard._reset()
            Memory._reset()
            Interrupts._reset()
            SysCall._reset()
            boot_func.func()
            ops = Screen._get_operations().copy()
            # Also fold memory ops recorded during this boot function
            for mop in Memory._get_operations():
                ops.append(mop)
            self._func_ops[boot_func.name] = ops
            self._symbol_map.append(
                {
                    "kind": "boot",
                    "name": boot_func.name,
                    "priority": str(boot_func.priority),
                }
            )
            for op in ops:
                if op.get("type") == "print" and "text" in op:
                    label = f"str_{self._string_counter}"
                    self._string_counter += 1
                    self._strings.append((label, op["text"]))
                    op["_string_label"] = label

        for handler in self.kernel._keypress_handlers:
            self._symbol_map.append({"kind": "keypress", "name": handler.name})

        return self._emit_c(sorted_funcs)

    def generate_asm(self) -> str:
        """Compatibility: return a comment pointing at C glue."""
        return (
            "; pyOS no longer emits full kernels as Assembly.\n"
            "; Bootloader remains ASM; kernel runtime is C.\n"
            "; Use kernel.compile() for generated C glue.\n"
        )

    def get_symbol_map(self) -> List[Dict[str, str]]:
        return list(self._symbol_map)

    def _c_escape(self, text: str) -> str:
        return (
            text.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t")
        )

    def _emit_c(self, sorted_funcs: list) -> str:
        cfg = self.kernel.config
        stack_top = 0x90000
        # Keep stack in low memory like classic bootloader layout
        heap_start = 0x200000
        heap_size = cfg.heap_size
        enable_irq = "PYOS_TRUE" if cfg.enable_interrupts else "PYOS_FALSE"
        has_key = "PYOS_TRUE" if self._has_keypress else "PYOS_FALSE"
        # note: values must match types.h macros

        lines: List[str] = []
        lines.append("/* Generated by pyOS — do not edit by hand */")
        lines.append('#include "kernel.h"')
        lines.append('#include "screen.h"')
        lines.append('#include "heap.h"')
        lines.append('#include "debug.h"')
        lines.append("")
        lines.append("KernelConfig g_kernel_config = {")
        lines.append(f"    .stack_top = 0x{stack_top:X},")
        lines.append(f"    .heap_start = 0x{heap_start:X},")
        lines.append(f"    .heap_size = {heap_size}u,")
        lines.append(f"    .enable_interrupts = {enable_irq},")
        lines.append(f"    .has_keypress_handler = {has_key},")
        lines.append("};")
        lines.append("")

        for label, text in self._strings:
            lines.append(f'static const char {label}[] = "{self._c_escape(text)}";')
        lines.append("")

        for boot_func in sorted_funcs:
            lines.append(f"/* @kernel.on_boot {boot_func.name} (priority={boot_func.priority}) */")
            lines.append(f"static void boot_{boot_func.name}(void) {{")
            lines.append(f'    debug_log("enter @kernel.on_boot {boot_func.name}");')
            for op in self._func_ops.get(boot_func.name, []):
                lines.extend(self._emit_op(op, boot_func.name))
            lines.append("}")
            lines.append("")

        lines.append("void pyos_user_boot(void) {")
        for boot_func in sorted_funcs:
            lines.append(f"    boot_{boot_func.name}();")
        lines.append("}")
        lines.append("")

        lines.append("void pyos_user_keypress(char ch, u8 scancode) {")
        if self._has_keypress:
            lines.append("    (void)scancode;")
            lines.append("    if (ch) {")
            lines.append("        screen_putchar(ch);")
            lines.append("    }")
            for handler in self.kernel._keypress_handlers:
                lines.append(f'    debug_log("keypress -> {handler.name}");')
        else:
            lines.append("    (void)ch; (void)scancode;")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    def _emit_op(self, op: dict, func_name: str) -> List[str]:
        t = op.get("type")
        out: List[str] = []
        if t == "clear":
            out.append("    screen_clear();")
        elif t == "set_color":
            fg = op.get("foreground", 15)
            bg = op.get("background", 0)
            out.append(f"    screen_set_color({fg}, {bg});")
        elif t == "set_cursor":
            out.append(f"    screen_set_cursor({op.get('row', 0)}, {op.get('col', 0)});")
        elif t == "print":
            label = op.get("_string_label", "str_0")
            row = op.get("row")
            col = op.get("col")
            fg = op.get("foreground", 15)
            bg = op.get("background", 0)
            color = (bg << 4) | fg
            if row is not None and col is not None:
                out.append(f"    screen_print_at({label}, {row}, {col}, {color});")
            else:
                out.append(f"    screen_set_color({fg}, {bg});")
                out.append(f"    screen_print({label});")
        elif t == "print_char":
            ch = op.get("char", " ")
            ch_esc = self._c_escape(ch)
            fg = op.get("foreground", 15)
            bg = op.get("background", 0)
            color = (bg << 4) | fg
            out.append(
                f"    screen_print_char_at('{ch_esc}', {op.get('row', 0)}, {op.get('col', 0)}, {color});"
            )
        elif t == "malloc":
            size = op.get("size", 0)
            out.append(f"    (void)heap_malloc({size}u);")
        elif t == "allocate_static":
            size = op.get("size", 0)
            out.append(f"    (void)heap_malloc({size}u);")
        elif t in ("free", "memset", "memcpy", "scroll_up", "scroll_down",
                   "enable_cursor", "disable_cursor", "read_byte", "write_byte",
                   "read_word", "write_word", "read_dword", "write_dword",
                   "calloc", "realloc"):
            out.append(f"    /* skipped unsupported op at runtime glue: {t} */")
        else:
            out.append(f"    /* unknown op in {func_name}: {t} */")
        return out
